{
  "hash": "30ff26624ce5070e8a7a57f022ee9fc2",
  "result": {
    "engine": "jupyter",
    "markdown": "# Intro to Pytorch\n\n\nMost materials are based on @Godoy2022.\n\n\n\n## Linear regression (math) {#sec-linearregression_math}\n\nWe only consider the simplest case: simple linear regression (SLR). The idea is very simple. The dataset contains two variables (the independent variable $x$ and the response variable $y$.) The goal is to find the relation between $x$ and $y$ with the given dataset. We assume their relation is $y=b+wx$. How do we find $b$ and $w$?\n\nLet us first see an example. We would like to find the red line (which is the best fitted curve) shown below.\n\n::: {#ca075719 .cell execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-2-output-1.png){width=573 height=421}\n:::\n:::\n\n\n### Parameter space\n\nThe key here is to understand the idea of \"parameter space\". Since we already know that the function we are looking for has a formula $y=b+wx$, we could use the pair $(b, w)$ to denote different candidates of our answer. For example, the following plot show some possibilities in green dashed lines, while each possiblity is denoted by $(b, w)$. Then the problem is reworded as to find the best pair $(b, w)$.\n\n::: {#ee17edca .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-3-output-1.png){width=573 height=421}\n:::\n:::\n\n\n### Loss function\nThe \"best\" is defined in the following way. The dataset is given $\\{(x_i, y_i)\\}$. If we choose a pair of parameters $(b,w)$, we will have an estimated regression line, as well as a set of estimated $\\hat{y_i}$. The idea is to let the difference between $y_i$ and $\\hat{y_i}$ is as small as possible. In other words, a **loss function** $J$ is defined as follows:\n\n$$\nJ_{\\{(x_i,y_i)\\}}(b,w)=\\frac1N\\sum_{i=1}^N(y_i-\\hat{y_i})^2=\\frac1N\\sum_{i=1}^N(y_i-b-wx_i)^2\n$$\nand we are expected to find the $(b,w)$ such that the loss function is minimized. The contour map of $J$ is shown below. \n\n::: {#f17b34dc .cell execution_count=3}\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nText(0, 0.5, 'w')\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-4-output-2.png){width=574 height=441}\n:::\n:::\n\n\n### Gradient Descent\n\nWe use a technique called \"gradient descent\" to find the global minimal of $J$. We start from a random point. For example $(1.0, 1.5)$. Then we find a direction where the cost $J$ reduces the most, and move in that direction. This direction is computed by the gradient of the cost $J$, and this is the reason why the algorithm is called \"gradient descent\". After we get to a new point, we evaluate the new gradient and move in the new direction. The process is repeated and we are expected to get close to the minimal point after several iterations. Just like shown in the following plot.\n\n::: {#8a478eff .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-5-output-1.png){width=574 height=441}\n:::\n:::\n\n\nThe parameter updating rule is shown below. The $\\eta$ is called the **learning rate**. It is a hyperparameter that is used to control the learning process. \n\n::: {.callout-note collapse=\"true\"}\n# Learning rate $\\eta$\nGenerally speaking, larger $\\eta$ will move faster to the global minimal, but might be jumpy which cause it harder to converge. On the other side, smaller $\\eta$ moves in a more stable fashion, but may take a long time to converge. See the following examples.\n\n::: {#b1838c19 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-6-output-1.png){width=577 height=436}\n:::\n:::\n\n\nIn the first example, $\\eta$ is too small, that after 200 iterations it is not very close to the minimal. In the second example, $\\eta$ becomes large. Although it gets to somewhere near the minimal, the path is very jumpy. It is able to converge only because the problem is indeed an easy one.\n:::\n\nWe may record the curve of the cost function.\n\n::: {#fd6ad1d7 .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\nAfter 200 iterations, the parameters are (2.297896055403118, 1.2006904171404507).\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](intro_files/figure-html/cell-7-output-2.png){width=593 height=435}\n:::\n:::\n\n\nThe cost is close to $0$ after 200 iterations and seems to be convergent. Therefore we believe that we are close to the minimal point. The point we get is (2.297896055403118, 1.2006904171404507).\n\n\n\n\n\n### Summary\n\nLet us summarize the example above and generalize it to the general case. \n\n1. Let $\\{(X_i, y_i)\\}$ be a given dataset. Assume that $y=f_{\\Theta}(X)$ where $\\Theta$ is the set of all parameters. \n2. The cost function $J_{\\Theta, \\{(X_i, y_i)\\}}$ is defined. \n3. To find the minimal point of the cost function, the gradient descent is applied: \n   - Start from a random initial point $\\theta_0$.\n   - Compute the gradient $\\nabla J$ and update $\\theta_i=\\theta_{i-1}- \\eta \\nabla J$ and repeat the process multiple times.\n   - Draw the learning curve and determine when to stop. Then we get the estimated best parameters $\\hat{\\Theta}$.\n4. Our model under this setting is sovled. We then turn to evaluation phase.\n\n\n::: {.callout-note}\nThe above process can be further developped. We will discuss many of them in details later.\n\n1. The cost function is related to each concerte problem.\n2. To compute the gradient of the cost function, chain rule is usually used. In the setting of MLP which we will discuss later, the gradient computations with chain rule are summarized as the so-called **Back propagation**. \n3. We go through the data points to compute the graident. How many points do we use? What is the frenqucy to update the gradient? This belongs to the topic of **mini-batch**.\n4. Even when we know that the graident gives the best direction, sometimes we don't really want to go in that direction, but make some modifications for some reason. To modify the direction, as well as choosing the learning rate $\\eta$, is the subject of **optimizers**.\n:::\n\n\n## Linear regression (`numpy`)\n\n\n## Linear regression (`PyTorch`)\n\n\n## Rewrite in classes\n\ns\n\n\n## Exercises\n\n\n\n::: {exr-}\nTry to reconstruct all the plots in Section @sec-linearregression_math.\n:::\n\n",
    "supporting": [
      "intro_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}